### PR TITLE
Some updates on top of v1.2rc

### PR DESCRIPTION
**Pull request by delarosatrevin**
* Gpu standardization
  * The executor was modified to use many GPUs in threads
  * Motiocor2 protocol was modified to use the GPU standardization
* Relion changes
  * rlnRandomSubset is propagated to be used in LocalRec
  * The picking wizard will pick all micrographs in the subset (and load initial picked coords)
  * Mask 3D protocol was updated (labels and help) and test added
* Initial code for Rubinstein programs (from Shalini)
   * align movies and particles

### CODE REVIEW

**Comment by azazellochg** [comment]
Hi @delarosatrevin , could you tell me what the following means?
- The executor was modified to use many GPUs in threads - does this mean some link between number of threads in gui and gpu list?
- about picking wizard: how was it working before the change? (sorry, I don't use relion for picking..)

**Comment by delarosatrevin** [comment]
Sure.
* The executor was modified to use many GPUs in threads - does this mean some link between number of threads in gui and gpu list?
Yes, that's it. For example, in MotionCor2...if you set 3 threads and GPU List = 0 1, then thread 0 will be master and thread 1 will use gpu 0 and thread 2 in gpu 1. If you use 5, then two threads on gpu 0 and two threads in gpu 1 (which is not recommended with the new version of MC2). If you use 3 threads and 0 1 2 3 gpus, then again 1 master and thread 1 will have gpu 0 1 and thread 2 gpu 2 3. This will apply in the same way to other protocols that use STEPS_PARALLEL, if they define the specific names of parameters: 'useGPU' and 'gpuList' (I think I will need to write a doc page about this)

* about picking wizard: how was it working before the change? (sorry, I don't use relion for picking..)
It was working to launch the picking program for only one micrograph...which in some cases is as slow as picking all of them. So, not it launch for all (those in the subset) and load the resulting coordinates...and then, when you move from one mic to another, it does not launch the picking program again. I'm not sure if this could also benefits other picking wizards as Gautomatch.

**Comment by azazellochg** [comment]
Thank you!
1. So, basically it works like MPI with a master thread on CPU and the "slaves" on the gpus (alternating). This is somewhat similar to relion2:

>  The option 'Which GPUs to use' can be used to specify which MPI process is run on which card, e.g. "0:1:2:3" means that the slaves 1-4 will run on cards 0-3. Note that the master (mpi-rank 0) will not use any GPU: it will merely orchestrate the calculations

2. Aha! That's nice if picking time is almost the same for 1 or 3-4 mics. For Gautomatch this is not useful, since picking takes a fraction of second, also re-run is not needed always [(here)](https://github.com/I2PC/scipion/issues/1124)

I will check relion/motioncor2 changes and tell you, mask protocol labels looks ok :)

**Review by azazellochg — APPROVED** [review]
Ok, it seems to work very nicely! I am impressed how big the speed gain is for motioncor2 running in parallel on multiple GPUs!!!
One minor thing, maybe in Xmipp picker to rename "Inter-particles distance" to "Inter-particle distance (A)" to avoid confusion that it is not in pixels. I know there is not much space in GUI but...

**Pull request merged**
